# Generated by Django 3.0 on 2019-12-30 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_text',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='upordown',
            new_name='change',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='boast',
            new_name='is_boast',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='pub_date',
            new_name='time',
        ),
    ]
